version: '3.8'

services:
  idea-ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: idea-ecommerce
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - idea-network
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "node", "-e", "http.get('http://localhost:3000/api/health', (res) => { if (res.statusCode === 200) process.exit(0); else process.exit(1); }).on('error', () => process.exit(1));"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Local PostgreSQL (if not using external service like Neon)
  postgres:
    image: postgres:15-alpine
    container_name: idea-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DATABASE:-idea}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - idea-network
    profiles:
      - local-db

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: idea-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - idea-ecommerce
    networks:
      - idea-network
    profiles:
      - nginx

volumes:
  postgres_data:

networks:
  idea-network:
    driver: bridge 